In [2]:
import os
import numpy as np
from PIL import Image
import json
import pefile
from tqdm.auto import tqdm

/home/netsec/hs-AI/lib/python3.7/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [11]:
def getBinaryData(filepath):
    binaryValues = []
    file = open(filepath, "rb")
    data = file.read(1)  # read byte by byte
    while data !=b"":
        try:
            binaryValues.append(ord(data))  # store value to array
        except TypeError:
            pass
        data = file.read(1)  # get next byte value


    return binaryValues

In [25]:
def extract_static(filepath):
    binvalue = getBinaryData(filepath)
    pe = pefile.PE(filepath)
    pointer_to_raw_data = []
    for section in pe.sections:
        pointer_to_raw_data.append(hex(section.PointerToRawData))
    width = 256
    height = 256
    static_data = np.zeros((width, height,len(pointer_to_raw_data)+1))
    w = 0
    h = 0
    s = 0
    for i, v in enumerate(binvalue):
        for address in pointer_to_raw_data:
            if i==int(int(address, 16)):
                s+=1
                break
        if i%2==0:
            w = v
        else:
            h = v
            static_data[w][h][s]+=1
            w = 0
            v = 0
    return static_data

In [ ]:
def d_compress(data_array):
    return compressed_data

In [20]:
BENIGN_FILE_PATH = "./benign_raw_data/"
BENIGN_FILE_list = os.listdir(BENIGN_FILE_PATH)

In [36]:
len(BENIGN_FILE_list)

11803

In [40]:
for file_list in tqdm(BENIGN_FILE_list[7902:], total=len(BENIGN_FILE_list[7902:])):
    exted_data = extract_static(BENIGN_FILE_PATH+file_list)
    np.save('./benign_npy_data/'+file_list, exted_data)

100%|█████████████████████████████████████| 3901/3901 [2:11:03<00:00,  2.02s/it]


In [28]:
MAL_FILE_PATH = "./malware_raw_data/"
MAL_FILE_list = os.listdir(MAL_FILE_PATH)

In [32]:
for file_list in tqdm(MAL_FILE_list[6125:], total=len(MAL_FILE_list[6125:])):
    exted_data = extract_static(MAL_FILE_PATH+file_list)
    np.save('./malware_npy_data/'+file_list, exted_data)

100%|█████████████████████████████████████████| 996/996 [11:29<00:00,  1.45it/s]


In [ ]:
pe = pefile.PE(MAL_FILE_PATH+MAL_FILE_list[6124])

In [134]:
a=extract_static('./sample_data/mal/9601')

In [136]:
a.shape

(256, 256, 5)

In [140]:
b=extract_static('./sample_data/mal/9601')

In [ ]:
def 

In [193]:
a=a.reshape(-1,5)

In [191]:
a=a.reshape(256,256,5)

In [192]:
np.array_equal(a,b)

True

In [143]:
from sklearn.decomposition import PCA

In [178]:
pca = PCA(n_components=4)

In [195]:
pca.fit(a)

PCA(n_components=4)

In [196]:
a_pca = pca.transform(a)

In [197]:
a_pca=a_pca.reshape(256,256,4)

In [199]:
a_pca.max()

588.9379545498002

In [200]:
b.max()

384.0

In [41]:
import pandas as pd

/home/netsec/hs-AI/lib/python3.7/site-packages/pandas/compat/__init__.py:124: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)


In [42]:
df=pd.read_csv('./malware_api_call_sequence.csv')

In [43]:
df.drop('Unnamed: 0',axis=1, inplace=True)

In [45]:
MAL_FILE_PATH = "./malware_npy_data/"
MAL_FILE_list = os.listdir(MAL_FILE_PATH)
MAL_FILE_list.sort()

In [46]:
len(MAL_FILE_list)

7120

In [47]:
MAL_FILE_list[:5]

['00008a4647def264460c48f32eaf13c899234ca9.npy',
 '0000f08f89b171dc382913a0e570dc293e0ecbf0.npy',
 '000c71dcd6aced55190e12b0b1131aa611f9d720.npy',
 '0010d625e099a9858963e8cad4dec08bf35e9ed4.npy',
 '002756edd58c8d9c7817215382f377a8d3223e69.npy']

In [48]:
MAL_FILE_list[995:1000]

['22c526cd131585bf5cc73b41246d78898e6e6daf.npy',
 '22cb21ccc70d6667a17df32ba6094f961fcce8ca.npy',
 '22cbc8451fb392e9d82feac2256eeeb4611e645d.npy',
 '22cd86e37fb9cec0fa7ce2c7ea542ae85744db18.npy',
 '22d59f5e88e2a94a417672c663bec9d509206c25.npy']

In [56]:
dic = {'HashName':[],
       'api':[],
       'category':[],
       'mal':[]}

In [53]:
df.head()

HashName  \
0  00008a4647def264460c48f32eaf13c899234ca9   
1  0000f08f89b171dc382913a0e570dc293e0ecbf0   
2  000c71dcd6aced55190e12b0b1131aa611f9d720   
3  0010d625e099a9858963e8cad4dec08bf35e9ed4   
4  002756edd58c8d9c7817215382f377a8d3223e69   

                                                 api  \
0  ['LdrLoadDll', 'LdrGetProcedureAddress', 'LdrG...   
1  ['GetSystemTimeAsFileTime', 'LdrGetDllHandle',...   
2  ['LdrLoadDll', 'LdrGetProcedureAddress', 'LdrG...   
3  ['NtAllocateVirtualMemory', 'NtFreeVirtualMemo...   
4  ['NtAllocateVirtualMemory', 'NtFreeVirtualMemo...   

                                            category  mal  
0  ['system', 'system', 'system', 'system', 'syst...  1.0  
1  ['synchronisation', 'system', 'system', 'syste...  1.0  
2  ['system', 'system', 'system', 'system', 'syst...  1.0  
3  ['process', 'process', 'process', 'file', 'fil...  1.0  
4  ['process', 'process', 'process', 'file', 'fil...  1.0

In [57]:
df_data = pd.DataFrame(dic)

In [58]:
for i in MAL_FILE_list[:1000]:
    df_data = df_data.append(df[df['HashName']==os.path.splitext(i)[0]])

In [59]:
df_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   HashName  1000 non-null   object 
 1   api       1000 non-null   object 
 2   category  1000 non-null   object 
 3   mal       1000 non-null   float64
dtypes: float64(1), object(3)
memory usage: 39.1+ KB


In [60]:
df_data.to_csv('./aaa.csv')

In [57]:
def createGreyScaleImageSpecificWith(dataSet, outputfilename, mal, width=0,):
    if width == 0:
        size = len(dataSet)
        if size < 10240:
            width = 32
        elif 10240 <= size <= 10240*3:
            width = 64
        elif 10240*3 <= size <= 10240*6:
            width = 128
        elif 10240*6 <= size <= 10240*10:
            width = 256
        elif 10240*10 <= size <= 10240*20:
            width = 384
        elif 10240*20 <= size <= 10240*50:
            width = 512
        elif 10240*50 <= size <= 10240*100:
            width = 768
        else:
            width = 1024

    height = int(size/width)+1

    image = Image.new('L', (width, height))

    image.putdata(dataSet)

    imagename = outputfilename+".png"
    image = image.resize((256,256), 3)
    image.save("./images/"+ mal+ '/' + imagename)

In [ ]:
def createGreyScaleImageSpecificWith(dataSet, width=0):
    api_dic =  {1: (0,0,128), 
                2: (0,0,255), 
                3: (255,255,128), 
                4: (0,64,0), 
                5: (255,128,0), 
                6: (64,128,128),
                7: (255,0,128),
                8: (128,0,128),
                9: (0,255,0),
                10: (255,0,0),
                11: (128,0,0),
                12: (128,255,255),
                13: (255,128,128),
                14: (192,192,192),
                15: (128,64,0),
                16: (255,255,255)}

    height = int(size/width)+1

    image = Image.new('L', (width, height))

    image.putdata(dataSet)

    imagename = outputfilename+".png"
    image = image.resize((256,256), 3)
    image.save("./images/"+ mal+ '/' + imagename)

In [1]:
import os
import numpy as np
from PIL import Image
import json

In [2]:
import pandas as pd

/home/netsec/hs-AI/lib/python3.7/site-packages/pandas/compat/__init__.py:124: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)


In [58]:
def do_preprocessing(path, file, mal):
    base_name = os.path.splitext(file)[0]
    outputFilename = base_name
    binaryData = getBinaryData(path+base_name)
    createGreyScaleImageSpecificWith(binaryData, outputFilename, mal)

In [3]:
df_m = pd.read_csv('./extract_processed_mal_data.csv')
df_b = pd.read_csv('./extract_processed_ben_data.csv')

In [4]:
mal_list = df_m['HashName'].to_list()
ben_list = df_b['HashName'].to_list()

In [9]:
sorted(mal_list)[0]

'00420ff2763a6b6b9a73f70a42872fb6de085da9'

In [37]:
a=getBinaryData("./malware_raw_data/"+sorted(mal_list)[0])

In [51]:
for _ in range(64):
    a.append(0)

In [72]:
aa=np.array(a)

In [53]:
aa.shape

(79104,)

In [54]:
size = aa.shape[0]
if size < 10240:
    width = 32
elif 10240 <= size <= 10240*3:
    width = 64
elif 10240*3 <= size <= 10240*6:
    width = 128
elif 10240*6 <= size <= 10240*10:
    width = 256
elif 10240*10 <= size <= 10240*20:
    width = 384
elif 10240*20 <= size <= 10240*50:
    width = 512
elif 10240*50 <= size <= 10240*100:
    width = 768
else:
    width = 1024

In [55]:
width

256

In [56]:
aa.shape[0]/width

309.0

In [44]:
256*308

78848

In [45]:
78912-78848

64

In [63]:
np.set_printoptions(threshold=309)

In [75]:
aaa=aa.reshape((309,256))

In [76]:
print(aaa)

[[ 77  90 144 ...   0  15   1]
 [ 11   1   6 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 ...
 [111   0 110 ...  67  82  84]
 [ 46 100 108 ...   0   0   0]
 [ 98  53  49 ...   0   0   0]]


In [81]:
aaaa = aaa.tolist()

In [90]:
hh=[]
for i in aaaa:
    for j in i:
        h = format(j, 'x')
        hh.append(h)

In [94]:
print(" ".join(hh[:20]))

4d 5a 90 0 3 0 0 0 4 0 0 0 ff ff 0 0 b8 0 0 0


In [101]:
print(' '.join(map(str, a[:20])))

77 90 144 0 3 0 0 0 4 0 0 0 255 255 0 0 184 0 0 0


In [25]:
for _ in range(64):
    a.append(0)

In [59]:
for i in tqdm(mal_list, total=len(mal_list)):
    do_preprocessing("./malware_raw_data/", i, '1')

100%|███████████████████████████████████████| 1935/1935 [00:49<00:00, 39.49it/s]


In [60]:
for i in tqdm(ben_list, total=len(ben_list)):
    do_preprocessing("./benign_raw_data/", i, '0')

100%|███████████████████████████████████████| 1952/1952 [02:04<00:00, 15.70it/s]


In [47]:
import shutil

In [61]:
MAL_PATH='./images/1/'
MAL_FILES=os.listdir(MAL_PATH)

In [62]:
BEN_PATH='./images/0/'
BEN_FILES=os.listdir(BEN_PATH)

In [63]:
len_mal = len(MAL_FILES)
for idx, i in tqdm(enumerate(MAL_FILES), total=len(MAL_FILES)):
    if int(len_mal*0.9) >= idx > int(len_mal*0.8):
        shutil.move(MAL_PATH + i, './images/val/' + i)
    elif idx > int(len_mal*0.9):
        shutil.move(MAL_PATH + i, './images/test/' + i)
    else:
        shutil.move(MAL_PATH + i, './images/train/' + i)

100%|████████████████████████████████████| 1935/1935 [00:00<00:00, 60283.13it/s]


In [64]:
len_ben = len(BEN_FILES)
for idx, i in tqdm(enumerate(BEN_FILES), total=len(BEN_FILES)):
    if int(len_ben*0.9) >= idx > int(len_ben*0.8):
        shutil.move(BEN_PATH + i, './images/val/' + i)
    elif idx > int(len_ben*0.9):
        shutil.move(BEN_PATH + i, './images/test/' + i)
    else:
        shutil.move(BEN_PATH + i, './images/train/' + i)

100%|████████████████████████████████████| 1952/1952 [00:00<00:00, 51229.74it/s]
